name: "IndexNow"
on:
  schedule:
  # Scheduled in UTC.
  - cron:  '0 0,12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Run IndexNow
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://memv.ennbee.uk/sitemap.xml"
          since: 36
          since-unit: "month"
          key: ${{ secrets.INDEXNOW_KEY }}
