name: "IndexNow"
on:
  schedule:
  # Scheduled in UTC.
  - cron:  '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Run IndexNow
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://www.oddsandendpoints.co.uk/sitemap.xml"
          since: 5
          since-unit: "year"
          key: ${{ secrets.indexnow }}
